### ISSUE TITLE
pip install from git

### ISSUE THREAD

**Issue by nducros** [openspyrit/spas#21]
Salut Thomas, 

J'aimerais faire `pip install git+https://github.com/openspyrit/spas.git` mais cela ne copie pas le fichier [cie-cmf.txt](https://github.com/openspyrit/spas/blob/main/spas/cie-cmf.txt) dans `\lib\site-packages`

Aurais-tu une idée ?

**Comment by tbaudier** [comment]
Try with https://github.com/openspyrit/spas/tree/manifest

**Comment by nducros** [comment]
Works fine!
