### ISSUE TITLE
 Unable to use read_metadata()?

### ISSUE THREAD

**Issue by nducros** [openspyrit/spas#8]
Une idée ?

`_, acquisition_parameters, _, _ = read_metadata(meta_path)`

Gives 

```
Traceback (most recent call last):

  Input In [27] in <cell line: 1>
    _, acquisition_parameters, _, _ = read_metadata(meta_path)

  File c:\users\ducros\openspyrit\spas\spas\metadata.py:823 in read_metadata
    saved_acquisition_params.undo_readable_pattern_order()

  File c:\users\ducros\openspyrit\spas\spas\metadata.py:244 in undo_readable_pattern_order
    self.patterns_wp = self.patterns_wp.strip('[').strip(']').split(', ')

AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by Mahieu-Williame** [comment]
oui, j'ai ajouté cette fonction pour insérer les motif blanc (wp pour white pattern). Tu dois utiliser seulement le prog de reconstruction sans reconstruction et non le prog d'acquisition avec la reconstruction, tu confirmes ? il faut que je le mette à jour. je ferai ça demain.

**Comment by nducros** [comment]
Je reconstruis les données du papier OE (donc v1.2 ?).
Dans un premier temps, j'avais juste besoin de read_metadata(), pas des fonctions de reconstruction. Donc je dirais que je confirme, si j'ai bien compris ta question.

**Comment by Mahieu-Williame** [comment]
voilà, j'ai mis une rustine, en fait je n'enregistre pas la variable patterns_wp, c'est pour ça qu'il n'a pas la méthode "strip". j'ai mis la fonction "Try" devant, donc ça passe maintenant.

**Comment by nducros** [comment]
Impec, c'est OK chez moi !
